### ISSUE TITLE
CheckSandBox Error!

### ISSUE THREAD

**Issue by Pwn0x01** [icyguider/Shhhloader#29] opened 2023-04-19 08:49 UTC
When I enable the checksandbox option, the program does not execute properly and crashes. However, when I disable the checksandbox option, the program runs normally. Upon analyzing the program with IDA, I found that the syscall function instruction before getting the function address is blank. Can the author please check the code to see if there are any issues?

**Comment by icyguider** [comment] 2023-04-19 16:40
Hi @Pwn0x01.

Thank you for the issue. I was able to narrow down the bug you are referencing. Specifically, the sleep and dll sandbox checks fail when used with GetSyscallStub (SW2 & SW3 were not affected). This is because I recently moved the syscall declarations after the sandbox checks, which caused those specific checks to fail as they use/depend on syscalls.

I've just pushed an update to address this. It seems to be working now, so please test it out and let me know if you have any issues. Thank you for reporting this bug, I really appreciate it!

**Comment by Pwn0x01** [comment] 2023-04-20 03:53
I used this command. 
`python3 Shhhloader.py test.raw -m CurrentThread -u -w -sc GetSyscallStub -p explore.exe -s username -sa tony -v -o test.exe` and 
`python3 Shhhloader.py test.raw -m CurrentThread -u -w -sc none -p explore.exe -s username -sa tony -v -o test.exe`，the generated program cannot run.finally I used this command
`python3 Shhhloader.py test.raw -m CurrentThread -u -w -sc none -p explore.exe -ns -v -o test.exe`,it can run，So it seems that there are some issues with the sandbox option.

**Comment by icyguider** [comment] 2023-04-20 11:09
@Pwn0x01,

In the examples you provided, you are setting a sandbox check for the username "tony". This is my username... so unless the system you are testing this on has the same username as mine, the sandbox check will fail as it was designed to do.

I confirmed yesterday after extensive testing that all sandbox checks are working as designed, so I think at this point you are probably just using it incorrectly as described above. I did make a short video showing how, for example, the username sandbox check works perfectly fine when provided a correct argument:

<details>
  <summary>See Video</summary>
<video src="https://user-images.githubusercontent.com/79864975/233347148-175d44f5-413b-4655-bf77-ec674238f2e2.mp4"></video>
</details>

I will close this issue as now it seems related to your usage rather than an actual bug in the tool.

**Closed by icyguider** 2023-04-20 11:09 UTC

**Comment by Pwn0x01** [comment] 2023-04-21 03:02
thanks,:)
It seems that I misunderstood the meaning of sandbox username detection. Most sandbox username detections that I have seen are based on a blacklist mechanism, which means that if the program detects a username that is similar to a known sandbox username, it will not run. For example, if someone named their sandbox "tony", then a program with a sandbox username detection mechanism might not run if it detects this username. However, the sandbox username detection mechanism in your program is based on a whitelist mechanism, which means that only specific usernames are allowed to run.
